version: '3.4'

services:
  tatarby.simulators.api:
    image: ${DOCKER_REGISTRY-}tatarbysimulatorsapi
    build:
      context: .
      dockerfile: tatarby.simulators.api/Dockerfile
    ports:
      - '8085:8080'

  tatarby.ml.api:
    image: ${DOCKER_REGISTRY-}tatarbymlapi
    build:
      context: .
      dockerfile: tatarby.ml.api/Dockerfile
    ports:
      - '8086:8080'